import os
from astropy.io import fits
from astropy.wcs import WCS

def wcs_add(infile, headfile, outfile=None, force=False, verbose=True):
    """
    Embed the WCS solution from a SCAMP .head file into the FITS image.
    
    Args:
        infile (str): Path to the original FITS image.
        headfile (str): Path to the .head file generated by SCAMP.
        outfile (str, optional): Path to save the result. 
                                 If None, input file is overwritten.
        force (bool): If True, overwrite WCS even if the input image 
                      already has one. Default is False.
    
    Raises:
        FileNotFoundError: If the .head file does not exist.
        ValueError: If the input image already has WCS and force is False.
    """
    
    # 1. Verify existence of the head file
    if not os.path.exists(headfile):
        raise FileNotFoundError(f"[hpastrometry-FATAL] SCAMP head file not found: {headfile}")
        
    # 2. Check if input image already has WCS
    # We perform a quick local check to ensure safety.
    has_existing_wcs = False
    try:
        with fits.open(infile, mode='readonly') as hdul:
            w = WCS(hdul[0].header, fix=False)
            if w.is_celestial:
                has_existing_wcs = True
    except Exception:
        pass # Ignore errors during check, proceed to add logic

    if has_existing_wcs and not force:
        raise ValueError(
            f"[hpastrometry-FATAL] Image '{infile}' already has WCS information. "
            "Use 'force=True' to overwrite it, or run 'wcs_strip' first."
        )

    if outfile is None:
        outfile = infile

    input_abs = os.path.abspath(infile)
    output_abs = os.path.abspath(outfile)
    
    open_mode = 'update' if input_abs == output_abs else 'readonly'

    # 3. Parse the SCAMP .head file
    # The .head file is an ASCII file formatted as FITS cards.
    try:
        scamp_header = fits.Header.fromtextfile(headfile)
    except Exception as e:
        raise ValueError(f"[hpastrometry-FATAL] Failed to parse .head file: {e}")

    # 4. Merge headers and save
    with fits.open(infile, mode=open_mode) as hdul:
        header = hdul[0].header
        
        # Update the FITS header with the SCAMP header.
        # This will overwrite existing keys with the same name.
        header.update(scamp_header)
        
        # Add a history record
        header.add_history(f"[hpastrometry-WCS] WCS updated using {os.path.basename(headfile)}")

        if outfile == infile:
            hdul.flush()
            if (verbose):
                print(f"[hpastrometry-WCS] WCS successfully added to: {infile}")
        else:
            hdul.writeto(outfile, overwrite=True)
            if (verbose):
                print(f"[hpastrometry-WCS] WCS added and saved to new file: {outfile}")